adding some lsb function missing in redhat, makes the script portable but adds unnecessary code will fix when  i figure out a more portable way of providing the

diff --git a/dinnerplated b/dinnerplated
--- a/dinnerplated
+++ b/dinnerplated
@@ -20,6 +20,38 @@ d_stop () {
         start-stop-daemon --name $DEAMON_NAME --stop --retry 5 --name $DEAMON_NAME
           log_end_msg $?
 }
+#i know this is a bad idea, but its a nice quick fix till i figure out how to make the ```status``` option portable
+status_of_proc () {
+    local pidfile daemon name status
+
+    pidfile=
+    OPTIND=1
+    while getopts p: opt ; do
+        case "$opt" in
+            p)  pidfile="$OPTARG";;
+        esac
+    done
+    shift $(($OPTIND - 1))
+
+    if [ -n "$pidfile" ]; then
+        pidfile="-p $pidfile"
+    fi
+    daemon="$1"
+    name="$2"
+
+    status="0"
+    pidofproc $pidfile $daemon >/dev/null || status="$?"
+    if [ "$status" = 0 ]; then
+        log_success_msg "$name is running"
+        return 0
+    elif [ "$status" = 4 ]; then
+        log_failure_msg "could not access PID file for $name"
+        return $status
+    else
+        log_failure_msg "$name is not running"
+        return $status
+    fi
+}
 
 case "$1" in
 
